name: CI
on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master
jobs:
    build:
        name: 'Build and Push'
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [23]
                os: [ubuntu-latest]
        
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'yarn'
            
            - name: Install Dependencies
              run: yarn

            - name: Running Tests
              run: yarn test

            - name: Login into the Container Registry
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
              
            - name: Build Docker Image
              run: docker build -t bielsanttos/aula-ci-cd:latest .

            - name: Push Docker Image to DockerHub
              run: docker push bielsanttos/aula-ci-cd:latest
              
